name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Doctest
      id: doctest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Doctest
        setup-command: npm install
        command: npm test
        timeout: 10
    - name: structure
      id: structure
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: structure
        setup-command: npm install
        command: npm structure
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DOCTEST_RESULTS: "${{steps.doctest.outputs.result}}"
        STRUCTURE_RESULTS: "${{steps.structure.outputs.result}}"
      with:
        runners: doctest,structure
